#############################################################################
# Makefile for building: project
# Generated by qmake (2.01a) (Qt 4.5.0) on: ?? 11? 4 20:50:08 2013
# Project:  project.pro
# Template: app
# Command: /usr/bin/amake -unix -o Makefile project.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QtEmbedded-4.5.0-arm/mkspecs/qws/linux-arm-g++ -I. -I../../QtEmbedded-4.5.0-arm/include/QtCore -I../../QtEmbedded-4.5.0-arm/include/QtNetwork -I../../QtEmbedded-4.5.0-arm/include/QtGui -I../../QtEmbedded-4.5.0-arm/include/QtSql -I../../QtEmbedded-4.5.0-arm/include -I. -Isqlite -IinputMethod -I/opt/sqlite-3.7.0/build/target/include -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib -L/opt/sqlite-3.7.0/build/target/lib -lsqlite3 -lQtSql -L/tslib/lib -L/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib -lQtGui -lts -lQtNetwork -lQtCore -lm -lrt -ldl -lpthread
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /usr/bin/amake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = data.cpp \
		draw.cpp \
		filelistmodel.cpp \
		filelistview.cpp \
		main.cpp \
		mainwin.cpp \
		myview.cpp \
		parameter.cpp \
		player.cpp \
		plotter.cpp \
		thread.cpp \
		win_1.cpp \
		win_2.cpp \
		win_3.cpp \
		win_4.cpp \
		win_data.cpp \
		win_passwd.cpp \
		win_start.cpp \
		win_system.cpp \
		win_video.cpp \
		inputMethod/Config.cpp \
		inputMethod/PinyinEngine.cpp \
		inputMethod/PinyinFrame.cpp \
		inputMethod/PinyinPhrase.cpp \
		inputMethod/public.cpp \
		inputMethod/scim_pinyin.cpp \
		sqlite/databaseStand.cpp \
		win_dateinput.cpp moc_data.cpp \
		moc_draw.cpp \
		moc_filelistmodel.cpp \
		moc_filelistview.cpp \
		moc_mainwin.cpp \
		moc_myview.cpp \
		moc_player.cpp \
		moc_plotter.cpp \
		moc_thread.cpp \
		moc_win_1.cpp \
		moc_win_2.cpp \
		moc_win_3.cpp \
		moc_win_4.cpp \
		moc_win_data.cpp \
		moc_win_passwd.cpp \
		moc_win_start.cpp \
		moc_win_system.cpp \
		moc_win_video.cpp \
		moc_PinyinFrame.cpp \
		moc_databaseStand.cpp \
		moc_win_dateinput.cpp \
		qrc_resource.cpp
OBJECTS       = data.o \
		draw.o \
		filelistmodel.o \
		filelistview.o \
		main.o \
		mainwin.o \
		myview.o \
		parameter.o \
		player.o \
		plotter.o \
		thread.o \
		win_1.o \
		win_2.o \
		win_3.o \
		win_4.o \
		win_data.o \
		win_passwd.o \
		win_start.o \
		win_system.o \
		win_video.o \
		Config.o \
		PinyinEngine.o \
		PinyinFrame.o \
		PinyinPhrase.o \
		public.o \
		scim_pinyin.o \
		databaseStand.o \
		win_dateinput.o \
		moc_data.o \
		moc_draw.o \
		moc_filelistmodel.o \
		moc_filelistview.o \
		moc_mainwin.o \
		moc_myview.o \
		moc_player.o \
		moc_plotter.o \
		moc_thread.o \
		moc_win_1.o \
		moc_win_2.o \
		moc_win_3.o \
		moc_win_4.o \
		moc_win_data.o \
		moc_win_passwd.o \
		moc_win_start.o \
		moc_win_system.o \
		moc_win_video.o \
		moc_PinyinFrame.o \
		moc_databaseStand.o \
		moc_win_dateinput.o \
		qrc_resource.o
DIST          = ../../QtEmbedded-4.5.0-arm/mkspecs/common/g++.conf \
		../../QtEmbedded-4.5.0-arm/mkspecs/common/unix.conf \
		../../QtEmbedded-4.5.0-arm/mkspecs/common/linux.conf \
		../../QtEmbedded-4.5.0-arm/mkspecs/common/qws.conf \
		../../QtEmbedded-4.5.0-arm/mkspecs/qconfig.pri \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/qt_functions.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/qt_config.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/exclusive_builds.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/default_pre.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/release.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/default_post.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/warn_on.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/qt.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/unix/thread.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/moc.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/resources.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/uic.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/yacc.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/lex.prf \
		project.pro
QMAKE_TARGET  = project
DESTDIR       = 
TARGET        = project

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project.pro  ../../QtEmbedded-4.5.0-arm/mkspecs/qws/linux-arm-g++/qmake.conf ../../QtEmbedded-4.5.0-arm/mkspecs/common/g++.conf \
		../../QtEmbedded-4.5.0-arm/mkspecs/common/unix.conf \
		../../QtEmbedded-4.5.0-arm/mkspecs/common/linux.conf \
		../../QtEmbedded-4.5.0-arm/mkspecs/common/qws.conf \
		../../QtEmbedded-4.5.0-arm/mkspecs/qconfig.pri \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/qt_functions.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/qt_config.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/exclusive_builds.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/default_pre.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/release.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/default_post.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/warn_on.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/qt.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/unix/thread.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/moc.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/resources.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/uic.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/yacc.prf \
		../../QtEmbedded-4.5.0-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib/libQtSql.prl \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib/libQtCore.prl \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib/libQtGui.prl \
		/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile project.pro
../../QtEmbedded-4.5.0-arm/mkspecs/common/g++.conf:
../../QtEmbedded-4.5.0-arm/mkspecs/common/unix.conf:
../../QtEmbedded-4.5.0-arm/mkspecs/common/linux.conf:
../../QtEmbedded-4.5.0-arm/mkspecs/common/qws.conf:
../../QtEmbedded-4.5.0-arm/mkspecs/qconfig.pri:
../../QtEmbedded-4.5.0-arm/mkspecs/features/qt_functions.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/qt_config.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/exclusive_builds.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/default_pre.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/release.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/default_post.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/warn_on.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/qt.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/unix/thread.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/moc.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/resources.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/uic.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/yacc.prf:
../../QtEmbedded-4.5.0-arm/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib/libQtSql.prl:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib/libQtCore.prl:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib/libQtGui.prl:
/usr/local/Trolltech/QtEmbedded-4.5.0-arm/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile project.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/project1.0.0 || $(MKDIR) .tmp/project1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/project1.0.0/ && $(COPY_FILE) --parents data.h draw.h filelistmodel.h filelistview.h mainwin.h mymodel.h myview.h parameter.h player.h plotter.h thread.h unicode_to_gbk.h win_1.h win_2.h win_3.h win_4.h win_data.h win_passwd.h win_start.h win_system.h win_video.h inputMethod/Config.h inputMethod/PinyinEngine.h inputMethod/PinyinFrame.h inputMethod/PinyinPhrase.h inputMethod/public.h inputMethod/scim_pinyin.h sqlite/databaseStand.h unicode_to_gbk.h win_dateinput.h .tmp/project1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/project1.0.0/ && $(COPY_FILE) --parents data.cpp draw.cpp filelistmodel.cpp filelistview.cpp main.cpp mainwin.cpp myview.cpp parameter.cpp player.cpp plotter.cpp thread.cpp win_1.cpp win_2.cpp win_3.cpp win_4.cpp win_data.cpp win_passwd.cpp win_start.cpp win_system.cpp win_video.cpp inputMethod/Config.cpp inputMethod/PinyinEngine.cpp inputMethod/PinyinFrame.cpp inputMethod/PinyinPhrase.cpp inputMethod/public.cpp inputMethod/scim_pinyin.cpp sqlite/databaseStand.cpp win_dateinput.cpp .tmp/project1.0.0/ && (cd `dirname .tmp/project1.0.0` && $(TAR) project1.0.0.tar project1.0.0 && $(COMPRESS) project1.0.0.tar) && $(MOVE) `dirname .tmp/project1.0.0`/project1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/project1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_data.cpp moc_draw.cpp moc_filelistmodel.cpp moc_filelistview.cpp moc_mainwin.cpp moc_myview.cpp moc_player.cpp moc_plotter.cpp moc_thread.cpp moc_win_1.cpp moc_win_2.cpp moc_win_3.cpp moc_win_4.cpp moc_win_data.cpp moc_win_passwd.cpp moc_win_start.cpp moc_win_system.cpp moc_win_video.cpp moc_PinyinFrame.cpp moc_databaseStand.cpp moc_win_dateinput.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_data.cpp moc_draw.cpp moc_filelistmodel.cpp moc_filelistview.cpp moc_mainwin.cpp moc_myview.cpp moc_player.cpp moc_plotter.cpp moc_thread.cpp moc_win_1.cpp moc_win_2.cpp moc_win_3.cpp moc_win_4.cpp moc_win_data.cpp moc_win_passwd.cpp moc_win_start.cpp moc_win_system.cpp moc_win_video.cpp moc_PinyinFrame.cpp moc_databaseStand.cpp moc_win_dateinput.cpp
moc_data.cpp: parameter.h \
		thread.h \
		data.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) data.h -o moc_data.cpp

moc_draw.cpp: draw.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) draw.h -o moc_draw.cpp

moc_filelistmodel.cpp: filelistmodel.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) filelistmodel.h -o moc_filelistmodel.cpp

moc_filelistview.cpp: filelistmodel.h \
		filelistview.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) filelistview.h -o moc_filelistview.cpp

moc_mainwin.cpp: mainwin.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) mainwin.h -o moc_mainwin.cpp

moc_myview.cpp: mymodel.h \
		myview.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) myview.h -o moc_myview.cpp

moc_player.cpp: player.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) player.h -o moc_player.cpp

moc_plotter.cpp: plotter.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) plotter.h -o moc_plotter.cpp

moc_thread.cpp: thread.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) thread.h -o moc_thread.cpp

moc_win_1.cpp: parameter.h \
		win_1.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_1.h -o moc_win_1.cpp

moc_win_2.cpp: filelistview.h \
		filelistmodel.h \
		win_2.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_2.h -o moc_win_2.cpp

moc_win_3.cpp: data.h \
		parameter.h \
		thread.h \
		draw.h \
		win_3.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_3.h -o moc_win_3.cpp

moc_win_4.cpp: win_4.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_4.h -o moc_win_4.cpp

moc_win_data.cpp: myview.h \
		mymodel.h \
		win_data.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_data.h -o moc_win_data.cpp

moc_win_passwd.cpp: win_passwd.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_passwd.h -o moc_win_passwd.cpp

moc_win_start.cpp: win_start.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_start.h -o moc_win_start.cpp

moc_win_system.cpp: win_data.h \
		myview.h \
		mymodel.h \
		win_system.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_system.h -o moc_win_system.cpp

moc_win_video.cpp: win_video.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_video.h -o moc_win_video.cpp

moc_PinyinFrame.cpp: inputMethod/PinyinEngine.h \
		inputMethod/scim_pinyin.h \
		inputMethod/PinyinPhrase.h \
		inputMethod/PinyinFrame.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) inputMethod/PinyinFrame.h -o moc_PinyinFrame.cpp

moc_databaseStand.cpp: sqlite/databaseStand.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) sqlite/databaseStand.h -o moc_databaseStand.cpp

moc_win_dateinput.cpp: win_dateinput.h
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/moc $(DEFINES) $(INCPATH) win_dateinput.h -o moc_win_dateinput.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		images/stop.png \
		images/start.png \
		images/play.png \
		images/mute.png \
		images/suspend.png \
		images/step.png \
		images/pause.png \
		images/vocal.png \
		images/openfile.png \
		images/backward.png
	/usr/local/Trolltech/QtEmbedded-4.5.0-arm/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

data.o: data.cpp data.h \
		parameter.h \
		thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data.o data.cpp

draw.o: draw.cpp draw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o draw.o draw.cpp

filelistmodel.o: filelistmodel.cpp filelistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filelistmodel.o filelistmodel.cpp

filelistview.o: filelistview.cpp filelistview.h \
		filelistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filelistview.o filelistview.cpp

main.o: main.cpp data.h \
		parameter.h \
		thread.h \
		win_1.h \
		win_2.h \
		filelistview.h \
		filelistmodel.h \
		win_3.h \
		draw.h \
		win_4.h \
		mainwin.h \
		win_passwd.h \
		win_system.h \
		win_data.h \
		myview.h \
		mymodel.h \
		win_start.h \
		win_dateinput.h \
		sqlite/databaseStand.h \
		inputMethod/PinyinFrame.h \
		inputMethod/PinyinEngine.h \
		inputMethod/scim_pinyin.h \
		inputMethod/PinyinPhrase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwin.o: mainwin.cpp mainwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwin.o mainwin.cpp

myview.o: myview.cpp myview.h \
		mymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myview.o myview.cpp

parameter.o: parameter.cpp parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameter.o parameter.cpp

player.o: player.cpp player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

plotter.o: plotter.cpp plotter.h \
		parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotter.o plotter.cpp

thread.o: thread.cpp thread.h \
		parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thread.o thread.cpp

win_1.o: win_1.cpp win_1.h \
		parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_1.o win_1.cpp

win_2.o: win_2.cpp win_2.h \
		filelistview.h \
		filelistmodel.h \
		plotter.h \
		parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_2.o win_2.cpp

win_3.o: win_3.cpp win_3.h \
		data.h \
		parameter.h \
		thread.h \
		draw.h \
		unicode_to_gbk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_3.o win_3.cpp

win_4.o: win_4.cpp win_4.h \
		win_video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_4.o win_4.cpp

win_data.o: win_data.cpp win_data.h \
		myview.h \
		mymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_data.o win_data.cpp

win_passwd.o: win_passwd.cpp win_passwd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_passwd.o win_passwd.cpp

win_start.o: win_start.cpp win_start.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_start.o win_start.cpp

win_system.o: win_system.cpp myview.h \
		mymodel.h \
		win_system.h \
		win_data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_system.o win_system.cpp

win_video.o: win_video.cpp win_video.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_video.o win_video.cpp

Config.o: inputMethod/Config.cpp inputMethod/Config.h \
		inputMethod/public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Config.o inputMethod/Config.cpp

PinyinEngine.o: inputMethod/PinyinEngine.cpp inputMethod/PinyinEngine.h \
		inputMethod/scim_pinyin.h \
		inputMethod/PinyinPhrase.h \
		inputMethod/public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PinyinEngine.o inputMethod/PinyinEngine.cpp

PinyinFrame.o: inputMethod/PinyinFrame.cpp inputMethod/PinyinFrame.h \
		inputMethod/PinyinEngine.h \
		inputMethod/scim_pinyin.h \
		inputMethod/PinyinPhrase.h \
		inputMethod/public.h \
		inputMethod/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PinyinFrame.o inputMethod/PinyinFrame.cpp

PinyinPhrase.o: inputMethod/PinyinPhrase.cpp inputMethod/PinyinPhrase.h \
		inputMethod/scim_pinyin.h \
		inputMethod/public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PinyinPhrase.o inputMethod/PinyinPhrase.cpp

public.o: inputMethod/public.cpp inputMethod/public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o public.o inputMethod/public.cpp

scim_pinyin.o: inputMethod/scim_pinyin.cpp inputMethod/scim_pinyin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scim_pinyin.o inputMethod/scim_pinyin.cpp

databaseStand.o: sqlite/databaseStand.cpp sqlite/databaseStand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databaseStand.o sqlite/databaseStand.cpp

win_dateinput.o: win_dateinput.cpp win_dateinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_dateinput.o win_dateinput.cpp

moc_data.o: moc_data.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_data.o moc_data.cpp

moc_draw.o: moc_draw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_draw.o moc_draw.cpp

moc_filelistmodel.o: moc_filelistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filelistmodel.o moc_filelistmodel.cpp

moc_filelistview.o: moc_filelistview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filelistview.o moc_filelistview.cpp

moc_mainwin.o: moc_mainwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwin.o moc_mainwin.cpp

moc_myview.o: moc_myview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myview.o moc_myview.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_plotter.o: moc_plotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plotter.o moc_plotter.cpp

moc_thread.o: moc_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thread.o moc_thread.cpp

moc_win_1.o: moc_win_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_1.o moc_win_1.cpp

moc_win_2.o: moc_win_2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_2.o moc_win_2.cpp

moc_win_3.o: moc_win_3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_3.o moc_win_3.cpp

moc_win_4.o: moc_win_4.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_4.o moc_win_4.cpp

moc_win_data.o: moc_win_data.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_data.o moc_win_data.cpp

moc_win_passwd.o: moc_win_passwd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_passwd.o moc_win_passwd.cpp

moc_win_start.o: moc_win_start.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_start.o moc_win_start.cpp

moc_win_system.o: moc_win_system.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_system.o moc_win_system.cpp

moc_win_video.o: moc_win_video.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_video.o moc_win_video.cpp

moc_PinyinFrame.o: moc_PinyinFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PinyinFrame.o moc_PinyinFrame.cpp

moc_databaseStand.o: moc_databaseStand.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_databaseStand.o moc_databaseStand.cpp

moc_win_dateinput.o: moc_win_dateinput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_dateinput.o moc_win_dateinput.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

